wifi:
    main_passwd: ENC[AES256_GCM,data:97hpL8hEuZ5GDJVh,iv:T6COY6OiApbfyIyYA6MBGy7aSUMdOH8/viutYBNfi20=,tag:H22ISpAr69wzBzOR+6PxmQ==,type:str]
wifi_env: ENC[AES256_GCM,data:zQUcxqr8uzgC8GAsUCUNLRI/oY04Vr4zY9zES+oYXawk9SpH++rbafAiNde/,iv:Ugi7c38UNE4t8NQXBErmATY9qQr7n13er1TExKR3QuI=,tag:zjRTJngORfZApN8PVwlnmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxaad6a86wag6s82tu0ugm4jnymrnhj38qg0n0j6v4y3hzsfqcdq7pgu9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MHF3cnlFMTlHdDJ4V2xG
            V3hZRFhncm1FSkRPZFhOLzNzZ2NsS0NDMXlJClVlajNIdFhmL0JKTSt6RHNoS0RI
            WWVPcnpTK3picDE0Z3ZGMlA5STMyQTgKLS0tIDV4bVhpenBEbHBCY0RTQmk5Rjc5
            UnRLUGFPQU0xWjlKOXY2Yk80VnJHZjgK8LwJDKP4TkicK+whdawGt9PCpBQTWrLT
            372w27Pk8HE88JHWLCLwkXGHU0BgZ0ACjRLBvszAgqqg2rowVEYQ+A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1napmf7e5tvhjclq4t8cf4z3y2j6l8meg3eld0ygwzz9w6tl48d8s3uuztl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNTdrdVYzbkI3aGNlZmpK
            NE1MUGdSL2pJMjRjc2YrMDVhbFlFWHBweVhvCjhZcnUxZC9VZUpvTnF5VFFudUls
            VWtUaUdmYlM4NXZWRFNRSGFyQTdaOTgKLS0tIHVlNlR3aTlqWktwU2xRVFA1Myti
            MUpRUEF4bXg1ait4bDlOUWxSS1JSWGMKk6HNHBFZzQq5Is9wMYw178H9L+MzV2oe
            BaHReJeGoI6lJ2zswAH4i28o10P10EAPloDJI5T3JpVtfqAoZiWhww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-22T20:50:43Z"
    mac: ENC[AES256_GCM,data:PbOIqu0VAlEsnNV4KroQJtT+1E1J1IIfzQoiLKkM+UZE+XCY6T6RqLahSB/LLwof/Lyt7KZEciLplSDVDn9Ty9/bIAslTPbraPSY9RNdqOcGG8JEiGO0XlxbPyO/17bFzGeDwnjW8W6B3F0l3owylF2D3q+VE0VetQfYcbdgrhk=,iv:v3iTAoxdXQa86rJKijo+aovFMKmPO1XHDn/NSBIfzBw=,tag:k83Vh8RcHcrGcIy/vNfSgA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
