hello: ENC[AES256_GCM,data:kuPFpFyyb7MPBV8PBEx3Q6NXxwV/I8X+RRN2+MsKlEO8yHiZ+w9ely4A4/LY8A==,iv:24HKU+29DNJdWWlOee95gAKUcLNWj7GJl7uywcuybrk=,tag:BCWUfqPV7r4d4kD4Pl9Mkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxaad6a86wag6s82tu0ugm4jnymrnhj38qg0n0j6v4y3hzsfqcdq7pgu9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MHF3cnlFMTlHdDJ4V2xG
            V3hZRFhncm1FSkRPZFhOLzNzZ2NsS0NDMXlJClVlajNIdFhmL0JKTSt6RHNoS0RI
            WWVPcnpTK3picDE0Z3ZGMlA5STMyQTgKLS0tIDV4bVhpenBEbHBCY0RTQmk5Rjc5
            UnRLUGFPQU0xWjlKOXY2Yk80VnJHZjgK8LwJDKP4TkicK+whdawGt9PCpBQTWrLT
            372w27Pk8HE88JHWLCLwkXGHU0BgZ0ACjRLBvszAgqqg2rowVEYQ+A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1napmf7e5tvhjclq4t8cf4z3y2j6l8meg3eld0ygwzz9w6tl48d8s3uuztl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNTdrdVYzbkI3aGNlZmpK
            NE1MUGdSL2pJMjRjc2YrMDVhbFlFWHBweVhvCjhZcnUxZC9VZUpvTnF5VFFudUls
            VWtUaUdmYlM4NXZWRFNRSGFyQTdaOTgKLS0tIHVlNlR3aTlqWktwU2xRVFA1Myti
            MUpRUEF4bXg1ait4bDlOUWxSS1JSWGMKk6HNHBFZzQq5Is9wMYw178H9L+MzV2oe
            BaHReJeGoI6lJ2zswAH4i28o10P10EAPloDJI5T3JpVtfqAoZiWhww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-17T21:07:53Z"
    mac: ENC[AES256_GCM,data:RUF4d86b2cahuHG0PzEMiisFO2XyQAZeJI2sdn1nSByMsK+98hVigUeeA/sz0xxI4BKCx3IDmvDQI5tQ1Hd2svcKkAGU4eur6qAiSqMmobOjzLc5exaEHZAB97chAg0tQe2chWFovpcfkA2NKMKl94zIJzAoTlobw49PCXyFHlI=,iv:wBn1ZrVKZELlcBtQQpmpO8e1R2ta4CQ0uMeYJvZYyQc=,tag:cpjssLo5YUEG/8+Usyq7uQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
